const defaultData={answered:0,correct:0,wrong:[],seen:[],lastResults:{}};

// Well-Architected 6 pillars: one scenario question per pillar
questions.push(
["ある企業は、AWS上のシステムについて、運用手順を継続的に改善し、小さく頻繁な変更を行い、運用から得た知見を今後の改善に活用したい。AWS Well-Architected Frameworkのどの柱に最も関連するか？",["信頼性","コスト最適化","運用上の優秀性","セキュリティ"],2,"正解は運用上の優秀性です。英語では Operational Excellence（オペレーショナルエクセレンス）といい、ワークロードを効果的に運用し、プロセスや手順を継続的に改善することを重視します。","クラウドの概念"],
["ある企業は、最小権限によるアクセス制御、データの暗号化、セキュリティイベントの検出を強化したい。AWS Well-Architected Frameworkのどの柱に最も関連するか？",["パフォーマンス効率","セキュリティ","持続可能性","運用上の優秀性"],1,"正解はセキュリティです。データ、システム、資産を保護し、ID管理、検出、インフラ保護、データ保護などを重視する柱です。","クラウドの概念"],
["あるWebサービスでは、一部のコンポーネントで障害が発生しても復旧し、意図した機能を継続して提供できる設計が求められている。AWS Well-Architected Frameworkのどの柱に最も関連するか？",["コスト最適化","セキュリティ","パフォーマンス効率","信頼性"],3,"正解は信頼性です。英語では Reliability といい、ワークロードが必要なときに意図した機能を正しく一貫して実行し、障害から回復できる能力を重視します。","クラウドの概念"],
["企業は、ワークロードの特性に応じて適切なコンピューティング、ストレージ、データベースを選択し、需要や技術の変化に合わせて効率を維持したい。AWS Well-Architected Frameworkのどの柱に最も関連するか？",["パフォーマンス効率","信頼性","運用上の優秀性","コスト最適化"],0,"正解はパフォーマンス効率です。英語では Performance Efficiency といい、システム要件を満たすためにコンピューティングリソースを効率的に利用し、需要や技術の変化にも効率を維持することを重視します。","クラウドの概念"],
["ある企業はAWS利用料を見直し、使用していないリソースを削除し、ワークロードに適したサイズへ変更して、必要以上の支出を減らしたい。AWS Well-Architected Frameworkのどの柱に最も関連するか？",["持続可能性","パフォーマンス効率","コスト最適化","信頼性"],2,"正解はコスト最適化です。英語では Cost Optimization といい、ビジネス価値を実現しながら不要な支出を避け、継続的に費用対効果を改善することを重視します。","クラウドの概念"],
["ある企業は、不要なリソースを減らし、コンピューティング資源の利用効率を高めることで、AWS上のワークロードによる環境への影響を継続的に抑えたい。AWS Well-Architected Frameworkのどの柱に最も関連するか？",["運用上の優秀性","持続可能性","セキュリティ","信頼性"],1,"正解は持続可能性です。英語では Sustainability（サステナビリティ）といい、エネルギー消費や必要なリソースを減らし、ワークロードによる環境への影響を継続的に改善することを重視します。","クラウドの概念"]
);

const STUDY_QUESTION_COUNT=questions.length;

let data;
try{
  data={...defaultData,...JSON.parse(localStorage.getItem('clf02-data-v3211')||'{}')};
}catch(e){data={...defaultData}}
if(!Array.isArray(data.wrong))data.wrong=[];
if(!Array.isArray(data.seen))data.seen=[];
if(!Number.isFinite(data.answered))data.answered=0;
if(!Number.isFinite(data.correct))data.correct=0;
if(!data.lastResults||typeof data.lastResults!=='object')data.lastResults={};
data.seen.forEach(id=>{if(data.lastResults[id]==null)data.lastResults[id]=data.wrong.includes(id)?'wrong':'correct'});
let session=[],idx=0,correct=0,locked=false;
function save(){localStorage.setItem('clf02-data-v3211',JSON.stringify(data));updateStats()}
function updateStats(){document.getElementById('answered').textContent=data.answered;document.getElementById('rate').textContent=(data.answered?Math.round(data.correct/data.answered*100):0)+'%';document.getElementById('wrongCount').textContent=data.wrong.filter(id=>id<STUDY_QUESTION_COUNT).length;let p=Math.round(data.seen.filter(id=>id<STUDY_QUESTION_COUNT).length/STUDY_QUESTION_COUNT*100);document.getElementById('progressText').textContent=p+'%';document.getElementById('progress').style.width=p+'%'}
const serviceTerms=['AWS Pricing Calculator','AWS Cost Explorer','AWS Budgets','AWS Artifact','AWS Organizations','AWS Marketplace','AWS Config','AWS KMS','AWS WAF','AWS Shield','Amazon CloudFront','Amazon Route 53','Amazon EC2','Amazon S3','Amazon EBS','Amazon EFS','Amazon RDS','Amazon DynamoDB','Amazon SQS','Amazon SNS','CloudFront','Route 53','Direct Connect','Auto Scaling','CloudTrail','CloudWatch','DynamoDB','Lambda','Aurora','EC2','S3 Glacier','S3','EBS','EFS','RDS','VPC','IAM','KMS','SQS','SNS','ELB'].sort((a,b)=>b.length-a.length);
const conceptTerms=['サーバーレス実行','リレーショナルDB','スケーラビリティ','APIアクティビティ','余剰キャパシティ','メッセージキュー','オブジェクトストレージ','ブロックストレージ','ファイルストレージ','オブジェクト','ブロック','アーカイブ','仮想サーバー','負荷分散','従量課金','高可用性','弾力性','俊敏性','最小権限','暗号鍵','メトリクス','NoSQL','Pub/Sub','専用線','名前解決','DNS','CDN','予算','分析','見積もり','可用性','責任共有モデル','Security OF the Cloud','Security IN the Cloud'].sort((a,b)=>b.length-a.length);
function buildMemoryBlanks(){
 const root=document.getElementById('study');
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(n){if(!n.nodeValue.trim())return NodeFilter.FILTER_REJECT;const p=n.parentElement;if(!p||p.closest('h2,h3,.tag,.sheet-hint,.btn,.memory-blank'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT;}});
 const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
 const esc=x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
 const all=[...serviceTerms.map(x=>({term:x,type:'service'})),...conceptTerms.map(x=>({term:x,type:'concept'}))].sort((a,b)=>b.term.length-a.term.length);
 const map=new Map(all.map(x=>[x.term,x.type]));
 const re=new RegExp('('+all.map(x=>esc(x.term)).join('|')+')','g');
 nodes.forEach(n=>{const text=n.nodeValue;if(!re.test(text)){re.lastIndex=0;return}re.lastIndex=0;const frag=document.createDocumentFragment();let last=0;let m;while((m=re.exec(text))){if(m.index>last)frag.appendChild(document.createTextNode(text.slice(last,m.index)));const span=document.createElement('span');const type=map.get(m[0])||'concept';span.className='memory-blank '+type+'-blank';span.textContent=m[0];span.title='タップで表示/非表示';frag.appendChild(span);last=m.index+m[0].length;}if(last<text.length)frag.appendChild(document.createTextNode(text.slice(last)));n.parentNode.replaceChild(frag,n);});
}
function setSheetMode(mode){const s=document.getElementById('study');s.classList.remove('sheet-red','sheet-green','sheet-both');if(mode==='red')s.classList.add('sheet-red');if(mode==='green')s.classList.add('sheet-green');if(mode==='both')s.classList.add('sheet-both');document.querySelectorAll('.memory-blank').forEach(n=>n.classList.remove('revealed'));document.querySelectorAll('.sheet-mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));localStorage.setItem('clf02-sheet-mode',mode);}
document.addEventListener('click',e=>{const n=e.target.closest('.memory-blank');if(!n)return;const s=document.getElementById('study');const hidden=(s.classList.contains('sheet-red')&&n.classList.contains('service-blank'))||(s.classList.contains('sheet-green')&&n.classList.contains('concept-blank'))||(s.classList.contains('sheet-both'));if(hidden){e.stopPropagation();n.classList.toggle('revealed')}});
function initQuestionListFilters(){const sel=document.getElementById('domainFilter');if(!sel||sel.dataset.ready)return;[...new Set(questions.slice(0,STUDY_QUESTION_COUNT).map(q=>q[4]))].forEach(d=>{const o=document.createElement('option');o.value=d;o.textContent=d;sel.appendChild(o)});sel.dataset.ready='1';}
function showQuestionList(){document.getElementById('home').classList.add('hidden');document.getElementById('study').classList.add('hidden');document.getElementById('quiz').classList.add('hidden');document.getElementById('result').classList.add('hidden');document.getElementById('floatingSheetBtn').classList.remove('show');document.getElementById('questionList').classList.remove('hidden');initQuestionListFilters();renderQuestionList();window.scrollTo(0,0);}
function renderQuestionList(){const body=document.getElementById('questionListBody');if(!body)return;const raw=(document.getElementById('questionSearch')?.value||'').trim().toLowerCase();const domain=document.getElementById('domainFilter')?.value||'';const rows=questions.slice(0,STUDY_QUESTION_COUNT).map((q,i)=>({q,i})).filter(({q})=>(!domain||q[4]===domain)&&(!raw||[q[0],q[4]].join(' ').toLowerCase().includes(raw)));document.getElementById('questionListSummary').textContent=`${rows.length} / ${STUDY_QUESTION_COUNT}問を表示`;body.innerHTML='';if(!rows.length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="5" class="list-empty">該当する問題がありません。</td>';body.appendChild(tr);return}rows.forEach(({q,i})=>{const tr=document.createElement('tr');const status=data.lastResults[i]||(data.seen.includes(i)?(data.wrong.includes(i)?'wrong':'correct'):'unanswered');const statusText=status==='correct'?'○ 正解':status==='wrong'?'× 不正解':'— 未回答';const statusClass=status==='correct'?'status-correct':status==='wrong'?'status-wrong':'status-unanswered';const no=document.createElement('td');no.className='col-no';no.textContent=`Q${i+1}`;const question=document.createElement('td');question.className='col-question';question.textContent=q[0];const ans=document.createElement('td');ans.className='col-answer';ans.textContent=Array.isArray(q[2])?q[2].map(x=>q[1][x]).join(' / '):q[1][q[2]];const dom=document.createElement('td');dom.className='col-domain';dom.textContent=q[4];const st=document.createElement('td');st.className='col-status '+statusClass;st.textContent=statusText;tr.append(no,question,ans,dom,st);body.appendChild(tr);});}
function showStudy(){document.getElementById('questionList').classList.add('hidden');document.getElementById('home').classList.add('hidden');document.getElementById('quiz').classList.add('hidden');document.getElementById('result').classList.add('hidden');document.getElementById('study').classList.remove('hidden');document.getElementById('floatingSheetBtn').classList.add('show');setSheetMode(localStorage.getItem('clf02-sheet-mode')||'off');window.scrollTo(0,0)}
function home(){document.getElementById('questionList').classList.add('hidden');document.getElementById('study').classList.add('hidden');document.getElementById('floatingSheetBtn').classList.remove('show');document.getElementById('home').classList.remove('hidden');document.getElementById('quiz').classList.add('hidden');document.getElementById('result').classList.add('hidden');updateStats()}
function start(n){let ids=[...Array(STUDY_QUESTION_COUNT).keys()].sort(()=>Math.random()-.5).slice(0,Math.min(n,STUDY_QUESTION_COUNT));begin(ids)}
function startWrong(){const ids=data.wrong.filter(id=>id<STUDY_QUESTION_COUNT);if(!ids.length){alert('復習する間違い問題はまだありません。');return}begin([...ids].sort(()=>Math.random()-.5))}
function begin(ids){session=ids;idx=0;correct=0;document.getElementById('questionList').classList.add('hidden');document.getElementById('home').classList.add('hidden');document.getElementById('result').classList.add('hidden');document.getElementById('quiz').classList.remove('hidden');render()}
function render(){locked=false;let id=session[idx],q=questions[id];document.getElementById('qnum').textContent=`${idx+1} / ${session.length}`;document.getElementById('domain').textContent=q[4];document.getElementById('question').textContent=q[0]+(Array.isArray(q[2])?'（複数選択）':'');let a=document.getElementById('answers');a.innerHTML='';q[1].forEach((x,i)=>{let b=document.createElement('button');b.className='answer';b.textContent=String.fromCharCode(65+i)+'. '+x;if(Array.isArray(q[2])){b.onclick=()=>b.classList.toggle('selected')}else{b.onclick=()=>answer(i,b)};a.appendChild(b)});if(Array.isArray(q[2])){let sb=document.createElement('button');sb.className='btn';sb.style.marginTop='12px';sb.textContent='選択した回答を確定';sb.onclick=()=>answerMulti(sb);a.appendChild(sb)}document.getElementById('explain').classList.add('hidden');document.getElementById('next').classList.add('hidden')}
